/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea_2;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.JOptionPane;

public class PeleaCom2 extends javax.swing.JFrame {
    Sansano jugador1;
    Sansano jugador2;
    int gameMode;
    static Duelo turnos = new Duelo();
    static int quienJuega;

    
    public PeleaCom2(Sansano jugador1 , Sansano jugador2 , int modeGame) {
        initComponents();
        texto1.setVisible(true);
        texto2.setVisible(true);
        texto3.setVisible(true);
        texto4.setVisible(true);
        texto5.setVisible(true);
        this.jugador1 = jugador1;
        this.jugador2 = jugador2;
        this.gameMode = modeGame;
        quienJuega = 0;
        name1.setText(this.jugador1.getNombre());
        name2.setText(this.jugador2.getNombre());
        String p1 = Integer.toString(jugador1.getPrioridad());
        String p2 = Integer.toString(jugador2.getPrioridad());
        prioridad1.setText(p1);
        prioridad2.setText(p2);
        texto3.setText("Elija su Modo,tenga en cuenta que:");
        texto4.setText(" -Modo defensivo, dota a la COM de un mazo ordenado con las cartas  de mayor curación al principio.");
        texto5.setText("-Modo Agresivo, dota a la COM de un mazo ordenado con las cartas  de mayor ataque al principio. ");
        jugador1.crearMazoAzar();
        if (gameMode == 0){
            Ataque.setEnabled(false);
            Defensa.setEnabled(false);
            continuar.setEnabled(false);
            
        }
        else{
            modoAgresivo.setVisible(false);
            modoDefensivo.setVisible(false);
            texto3.setText("Es el turno de "+jugador1.getNombre());
            Curso ejemplo1 = new Curso();
            Profesor ejemplo2 = new Profesor();
            Carrete ejemplo3 = new Carrete();
            if (jugador1.getMazo().get(turnos.getTurnos()).getClass()== ejemplo1.getClass()){
                Curso cardAux;
                cardAux = (Curso)jugador1.getMazo().get(turnos.getTurnos());
                texto4.setText("Tu carta es : "+cardAux.getNombre());
                texto5.setText(cardAux.getDescripcion());
            }
            else if (jugador1.getMazo().get(turnos.getTurnos()).getClass()== ejemplo2.getClass()){
                Profesor cardAux;
                cardAux = (Profesor)jugador1.getMazo().get(turnos.getTurnos());
                texto4.setText("Tu carta es : "+cardAux.getNombre());
                texto5.setText(cardAux.getDescripcion());

            }
            else if (jugador1.getMazo().get(turnos.getTurnos()).getClass()== ejemplo3.getClass()){
                Carrete cardAux;
                cardAux = (Carrete)jugador1.getMazo().get(turnos.getTurnos());
                texto4.setText("Tu carta es : "+cardAux.getNombre());
                texto5.setText(cardAux.getDescripcion());
            }
            
        }
        
        
        
        
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("tarea_2/imagenes/icono.png"));
        return retValue;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Picture1 = new javax.swing.JLabel();
        Pictur2 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        Priori = new javax.swing.JLabel();
        Priori2 = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        prioridad1 = new javax.swing.JLabel();
        prioridad2 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        modoDefensivo = new javax.swing.JButton();
        modoAgresivo = new javax.swing.JButton();
        texto3 = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        texto5 = new javax.swing.JLabel();
        Ataque = new javax.swing.JButton();
        Defensa = new javax.swing.JButton();
        continuar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SansaStone™ 2.0");
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Picture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/avatar_7cdd33eb8d4a_128.png"))); // NOI18N
        getContentPane().add(Picture1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 120));

        Pictur2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/avatar_eb0c4e0884c0_128.png"))); // NOI18N
        getContentPane().add(Pictur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));

        texto2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        texto2.setText("Jugador 2:");
        getContentPane().add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, -1, 20));

        Priori.setFont(new java.awt.Font("Consolas", 1, 10)); // NOI18N
        Priori.setText("Prioridad: ");
        getContentPane().add(Priori, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, -1, -1));

        Priori2.setFont(new java.awt.Font("Consolas", 1, 10)); // NOI18N
        Priori2.setText("Prioridad: ");
        getContentPane().add(Priori2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        texto1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        texto1.setText("Jugador 1:");
        getContentPane().add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 100, 20));
        getContentPane().add(prioridad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 110, 20));
        getContentPane().add(prioridad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 130, 20));
        getContentPane().add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 80, 20));

        modoDefensivo.setText("Modo Defensivo");
        modoDefensivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoDefensivoActionPerformed(evt);
            }
        });
        getContentPane().add(modoDefensivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 150, 40));

        modoAgresivo.setText("Modo Agresivo");
        modoAgresivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoAgresivoActionPerformed(evt);
            }
        });
        getContentPane().add(modoAgresivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 140, 40));

        texto3.setBackground(new java.awt.Color(255, 255, 255));
        texto3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        texto3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(texto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 380, 30));

        texto4.setBackground(new java.awt.Color(255, 255, 255));
        texto4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(texto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        texto5.setBackground(new java.awt.Color(255, 255, 255));
        texto5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(texto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        Ataque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/fencing-game-sword-fight-fence-combat-cross-128.png"))); // NOI18N
        Ataque.setBorder(null);
        Ataque.setBorderPainted(false);
        Ataque.setContentAreaFilled(false);
        Ataque.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Ataque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtaqueActionPerformed(evt);
            }
        });
        getContentPane().add(Ataque, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, -1, -1));

        Defensa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/1458264599_piggy_bank_savings_money_investment_budget_finance_icon-icons.com_55332.png"))); // NOI18N
        Defensa.setBorder(null);
        Defensa.setBorderPainted(false);
        Defensa.setContentAreaFilled(false);
        Defensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefensaActionPerformed(evt);
            }
        });
        getContentPane().add(Defensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, -1, -1));

        continuar.setText("Continuar");
        continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarActionPerformed(evt);
            }
        });
        getContentPane().add(continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 630, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/flat-wallpaper-3.png"))); // NOI18N
        Fondo.setPreferredSize(new java.awt.Dimension(720, 1024));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -150, 1050, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void modoDefensivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoDefensivoActionPerformed
        // TODO add your handling code here:
        Ataque.setEnabled(true);
        Defensa.setEnabled(true);
        jugador2.crearMazoDefensivo();
        modoDefensivo.setVisible(false);
        modoAgresivo.setVisible(false);
        if(quienJuega == 0){
            Curso ejemplo1 = new Curso();
            Profesor ejemplo2 = new Profesor();
            Carrete ejemplo3 = new Carrete();
            texto3.setText("Es el turno de "+jugador1.getNombre());
            if (jugador1.getMazo().get(turnos.getTurnos()).getClass()== ejemplo1.getClass()){
                Curso cardAux;
                cardAux = (Curso)jugador1.getMazo().get(turnos.getTurnos());
                texto4.setText("Tu carta es : "+cardAux.getNombre());
                texto5.setText(cardAux.getDescripcion());
            }
            else if (jugador1.getMazo().get(turnos.getTurnos()).getClass()== ejemplo2.getClass()){
                Profesor cardAux;
                cardAux = (Profesor)jugador1.getMazo().get(turnos.getTurnos());
                texto4.setText("Tu carta es : "+cardAux.getNombre());
                texto5.setText(cardAux.getDescripcion());

            }
            else if (jugador1.getMazo().get(turnos.getTurnos()).getClass()== ejemplo3.getClass()){
                Carrete cardAux;
                cardAux = (Carrete)jugador1.getMazo().get(turnos.getTurnos());
                texto4.setText("Tu carta es : "+cardAux.getNombre());
                texto5.setText(cardAux.getDescripcion());
            }
        }
        // --------------------------player 2--------------------------------
        else if(quienJuega == 1){
            Curso ejemplo1 = new Curso();
            Profesor ejemplo2 = new Profesor();
            Carrete ejemplo3 = new Carrete();
            texto3.setText("Es el turno de "+jugador2.getNombre());
            if (jugador2.getMazo().get(turnos.getTurnos()).getClass()== ejemplo1.getClass()){
                Curso cardAux;
                cardAux = (Curso)jugador2.getMazo().get(turnos.getTurnos());
                texto4.setText("Tu carta es : "+cardAux.getNombre());
                texto5.setText(cardAux.getDescripcion());
            }
            else if (jugador2.getMazo().get(turnos.getTurnos()).getClass()== ejemplo2.getClass()){
                Profesor cardAux;
                cardAux = (Profesor)jugador2.getMazo().get(turnos.getTurnos());
                texto4.setText("Tu carta es : "+cardAux.getNombre());
                texto5.setText(cardAux.getDescripcion());

            }
            else if (jugador2.getMazo().get(turnos.getTurnos()).getClass()== ejemplo3.getClass()){
                Carrete cardAux;
                cardAux = (Carrete)jugador2.getMazo().get(turnos.getTurnos());
                texto4.setText("Tu carta es : "+cardAux.getNombre());
                texto5.setText(cardAux.getDescripcion());
            }
            
        }
        
        
    }//GEN-LAST:event_modoDefensivoActionPerformed
    
    private void modoAgresivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoAgresivoActionPerformed
        // TODO add your handling code here:
        jugador2.crearMazoAgresivo();
        Ataque.setEnabled(true);
        Defensa.setEnabled(true);
        modoDefensivo.setVisible(false);
        modoAgresivo.setVisible(false);
        if(quienJuega == 0){
            Curso ejemplo1 = new Curso();
            Profesor ejemplo2 = new Profesor();
            Carrete ejemplo3 = new Carrete();
            texto3.setText("Es el turno de "+jugador1.getNombre());
            if (jugador1.getMazo().get(turnos.getTurnos()).getClass()== ejemplo1.getClass()){
                Curso cardAux;
                cardAux = (Curso)jugador1.getMazo().get(turnos.getTurnos());
                texto4.setText("Tu carta es : "+cardAux.getNombre());
                texto5.setText(cardAux.getDescripcion());
            }
            else if (jugador1.getMazo().get(turnos.getTurnos()).getClass()== ejemplo2.getClass()){
                Profesor cardAux;
                cardAux = (Profesor)jugador1.getMazo().get(turnos.getTurnos());
                texto4.setText("Tu carta es : "+cardAux.getNombre());
                texto5.setText(cardAux.getDescripcion());

            }
            else if (jugador1.getMazo().get(turnos.getTurnos()).getClass()== ejemplo3.getClass()){
                Carrete cardAux;
                cardAux = (Carrete)jugador1.getMazo().get(turnos.getTurnos());
                texto4.setText("Tu carta es : "+cardAux.getNombre());
                texto5.setText(cardAux.getDescripcion());
            }
        }
        // --------------------------player 2--------------------------------
        else if(quienJuega == 1){
            Curso ejemplo1 = new Curso();
            Profesor ejemplo2 = new Profesor();
            Carrete ejemplo3 = new Carrete();
            texto3.setText("Es el turno de "+jugador2.getNombre());
            if (jugador2.getMazo().get(turnos.getTurnos()).getClass()== ejemplo1.getClass()){
                Curso cardAux;
                cardAux = (Curso)jugador2.getMazo().get(turnos.getTurnos());
                texto4.setText("Tu carta es : "+cardAux.getNombre());
                texto5.setText(cardAux.getDescripcion());
            }
            else if (jugador2.getMazo().get(turnos.getTurnos()).getClass()== ejemplo2.getClass()){
                Profesor cardAux;
                cardAux = (Profesor)jugador2.getMazo().get(turnos.getTurnos());
                texto4.setText("Tu carta es : "+cardAux.getNombre());
                texto5.setText(cardAux.getDescripcion());

            }
            else if (jugador2.getMazo().get(turnos.getTurnos()).getClass()== ejemplo3.getClass()){
                Carrete cardAux;
                cardAux = (Carrete)jugador2.getMazo().get(turnos.getTurnos());
                texto4.setText("Tu carta es : "+cardAux.getNombre());
                texto5.setText(cardAux.getDescripcion());
            }
            
        }
        
        
    }//GEN-LAST:event_modoAgresivoActionPerformed
    
    private void DefensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefensaActionPerformed
        // TODO add your handling code here:            
        prioridad1.setText(Integer.toString(jugador1.getPrioridad()));
        prioridad2.setText(Integer.toString(jugador2.getPrioridad()));
        prioridad1.setVisible(true);
        prioridad2.setVisible(true);
        if(quienJuega == 0){
            Curso ejemplo1 = new Curso();
            Profesor ejemplo2 = new Profesor();
            Carrete ejemplo3 = new Carrete();
            
            if (jugador1.getMazo().get(turnos.getTurnos()).getClass()== ejemplo1.getClass()){
                Curso cardAux;
                cardAux = (Curso)jugador1.getMazo().get(turnos.getTurnos());
                cardAux.Aprobar(jugador1);
                //texto3.setVisible(false);
                texto3.setText(jugador1.getNombre());
                texto4.setText("Que bien te has curado");
                texto5.setText("tu prioridad ahora es :"+jugador1.getPrioridad());
                quienJuega = 1;
                Ataque.setEnabled(false);
                Defensa.setEnabled(false);
                continuar.setEnabled(true);
            }
            if (jugador1.getMazo().get(turnos.getTurnos()).getClass()== ejemplo2.getClass()){
                JOptionPane.showMessageDialog(null,"Esta carta solo te inflinge daño","Mensaje",JOptionPane.PLAIN_MESSAGE);

            }
            if (jugador1.getMazo().get(turnos.getTurnos()).getClass()== ejemplo3.getClass()){
                Carrete cardAux;
                cardAux = (Carrete)jugador1.getMazo().get(turnos.getTurnos());
                cardAux.Carretear(jugador1);
                texto3.setVisible(true);
                texto3.setText(jugador1.getNombre());
                texto4.setText("Que bien te has curado ");
                texto5.setText(jugador1.getNombre()+" tu prioridad ahora es :"+jugador1.getPrioridad());
                quienJuega = 1;
                Ataque.setEnabled(false);
                Defensa.setEnabled(false);
                continuar.setEnabled(true);
            }
        }
        // --------------------------player 2--------------------------------
        else if(quienJuega == 1){
            Curso ejemplo1 = new Curso();
            Profesor ejemplo2 = new Profesor();
            Carrete ejemplo3 = new Carrete();
           
            if (jugador2.getMazo().get(turnos.getTurnos()).getClass()== ejemplo1.getClass()){
                Curso cardAux;
                cardAux = (Curso)jugador2.getMazo().get(turnos.getTurnos());
                cardAux.Aprobar(jugador2);
                texto3.setText(jugador2.getNombre());
                texto4.setText("Que bien te has curado ");
                texto5.setText("tu prioridad ahora es :"+jugador2.getPrioridad());
                quienJuega = 0;
                Ataque.setEnabled(false);
                Defensa.setEnabled(false);
                continuar.setEnabled(true);
                turnos.addTurnos();
            }
            if (jugador2.getMazo().get(turnos.getTurnos()).getClass()== ejemplo2.getClass()){
                JOptionPane.showMessageDialog(null,"Esta carta solo te inflinge daño","Mensaje",JOptionPane.PLAIN_MESSAGE);

            }
            if (jugador2.getMazo().get(turnos.getTurnos()).getClass()== ejemplo3.getClass()){
                Carrete cardAux;
                cardAux = (Carrete)jugador2.getMazo().get(turnos.getTurnos());
                cardAux.Carretear(jugador2);
                texto3.setText(jugador2.getNombre());
                texto4.setText("Que bien te has curado ");
                texto5.setText("tu prioridad ahora es :"+jugador2.getPrioridad());
                quienJuega = 0;
                Ataque.setEnabled(false);
                Defensa.setEnabled(false);
                continuar.setEnabled(true);
                turnos.addTurnos();
            }            
        }
        
    }//GEN-LAST:event_DefensaActionPerformed

    private void AtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtaqueActionPerformed
        // TODO add your handling code here:  
        prioridad1.setText(Integer.toString(jugador1.getPrioridad()));
        prioridad2.setText(Integer.toString(jugador2.getPrioridad()));
        prioridad1.setVisible(true);
        prioridad2.setVisible(true);
        if(quienJuega == 0){
            Curso ejemplo1 = new Curso();
            Profesor ejemplo2 = new Profesor();
            Carrete ejemplo3 = new Carrete();
            
            if (jugador1.getMazo().get(turnos.getTurnos()).getClass()== ejemplo1.getClass()){
                Curso cardAux;
                cardAux = (Curso)jugador1.getMazo().get(turnos.getTurnos());
                cardAux.Reprobar(jugador2);
                texto3.setText(jugador1.getNombre());
                texto4.setText("Has atacado a "+ jugador2.getNombre());
                texto5.setText("Su prioridad ahora es :"+ jugador2.getPrioridad());
                quienJuega = 1;
                Ataque.setEnabled(false);
                Defensa.setEnabled(false);
                continuar.setEnabled(true);
            }
            if (jugador1.getMazo().get(turnos.getTurnos()).getClass()== ejemplo2.getClass()){
                Profesor cardAux;
                cardAux = (Profesor)jugador1.getMazo().get(turnos.getTurnos());
                cardAux.Recorregir(jugador1);
                texto3.setText(jugador1.getNombre());
                texto4.setText("Que lastima te has hecho daño");
                texto5.setText("Tu prioridad ahora es :" + jugador1.getPrioridad());
                quienJuega = 1;
                Ataque.setEnabled(false);
                Defensa.setEnabled(false);
                continuar.setEnabled(true);
                

            }
            if (jugador1.getMazo().get(turnos.getTurnos()).getClass()== ejemplo3.getClass()){
                JOptionPane.showMessageDialog(null,"Esta carta solo puede curarte","Mensaje",JOptionPane.PLAIN_MESSAGE);
            }
        }
        // --------------------------player 2--------------------------------
        else if(quienJuega == 1){
            Curso ejemplo1 = new Curso();
            Profesor ejemplo2 = new Profesor();
            Carrete ejemplo3 = new Carrete();
            texto3.setText("Es el turno de "+jugador2.getNombre());
            if (jugador2.getMazo().get(turnos.getTurnos()).getClass()== ejemplo1.getClass()){
                Curso cardAux;
                cardAux = (Curso)jugador2.getMazo().get(turnos.getTurnos());
                cardAux.Reprobar(jugador1);
                texto3.setText(jugador2.getNombre());
                texto4.setText("Has atacado a "+ jugador1.getNombre());
                texto5.setText("Su prioridad ahora es :"+ jugador1.getPrioridad());
                quienJuega = 0;
                Ataque.setEnabled(false);
                Defensa.setEnabled(false);
                continuar.setEnabled(true);
                turnos.addTurnos();
            }
            if (jugador2.getMazo().get(turnos.getTurnos()).getClass()== ejemplo2.getClass()){
                Profesor cardAux;
                cardAux = (Profesor)jugador2.getMazo().get(turnos.getTurnos());
                cardAux.Recorregir(jugador2);
                texto3.setText(jugador2.getNombre());
                texto4.setText("Que lastima te has hecho daño");
                texto5.setText("Tu prioridad ahora es :" + jugador2.getPrioridad());
                quienJuega = 1;
                Ataque.setEnabled(false);
                Defensa.setEnabled(false);
                continuar.setEnabled(true);
                turnos.addTurnos();

            }
            if (jugador2.getMazo().get(turnos.getTurnos()).getClass()== ejemplo3.getClass()){
                JOptionPane.showMessageDialog(null,"Esta carta solo puede curarte","Mensaje",JOptionPane.PLAIN_MESSAGE);
            }
            
        }
       
    }//GEN-LAST:event_AtaqueActionPerformed
    public static int activar=0;
    private void continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarActionPerformed
        // TODO add your handling code here:
        prioridad1.setText(Integer.toString(jugador1.getPrioridad()));
        prioridad2.setText(Integer.toString(jugador2.getPrioridad()));
        prioridad1.setVisible(true);
        prioridad2.setVisible(true);
        Ataque.setEnabled(true);
        Defensa.setEnabled(true);
        continuar.setEnabled(false);
        Curso ejemplo1 = new Curso();
        Profesor ejemplo2 = new Profesor();
        Carrete ejemplo3 = new Carrete();
        
        if ((jugador1.getPrioridad() == 0) || (turnos.getTurnos() == 0)){
                Podio podio = new Podio(); 
                podio.setLocationRelativeTo(null);
                podio.setVisible(true);
                this.dispose();  
                k
        }
        
        if (quienJuega == 0){
                texto3.setText("Es el turno de "+jugador1.getNombre());
                if (jugador1.getMazo().get(turnos.getTurnos()).getClass()== ejemplo1.getClass()){
                    Curso cardAux;
                    cardAux = (Curso)jugador1.getMazo().get(turnos.getTurnos());
                    texto4.setText("Tu carta es : "+cardAux.getNombre());
                    texto5.setText(cardAux.getDescripcion());
                }
                else if (jugador1.getMazo().get(turnos.getTurnos()).getClass()== ejemplo2.getClass()){
                    Profesor cardAux;
                    cardAux = (Profesor)jugador1.getMazo().get(turnos.getTurnos());
                    texto4.setText("Tu carta es : "+cardAux.getNombre());
                    texto5.setText(cardAux.getDescripcion());

                }
                else if (jugador1.getMazo().get(turnos.getTurnos()).getClass()== ejemplo3.getClass()){
                    Carrete cardAux;
                    cardAux = (Carrete)jugador1.getMazo().get(turnos.getTurnos());
                    texto4.setText("Tu carta es : "+cardAux.getNombre());
                    texto5.setText(cardAux.getDescripcion());
                }
            }
            
            if (quienJuega == 1){
                texto3.setText("Es el turno de "+jugador2.getNombre());
                if (jugador2.getMazo().get(turnos.getTurnos()).getClass()== ejemplo1.getClass()){
                    Curso cardAux;
                    cardAux = (Curso)jugador2.getMazo().get(turnos.getTurnos());
                    texto4.setText("Tu carta es : "+cardAux.getNombre());
                    texto5.setText(cardAux.getDescripcion());
                }
                else if (jugador2.getMazo().get(turnos.getTurnos()).getClass()== ejemplo2.getClass()){
                    Profesor cardAux;
                    cardAux = (Profesor)jugador2.getMazo().get(turnos.getTurnos());
                    texto4.setText("Tu carta es : "+cardAux.getNombre());
                    texto5.setText(cardAux.getDescripcion());

                }
                else if (jugador2.getMazo().get(turnos.getTurnos()).getClass()== ejemplo3.getClass()){
                    Carrete cardAux;
                    cardAux = (Carrete)jugador2.getMazo().get(turnos.getTurnos());
                    texto4.setText("Tu carta es : "+cardAux.getNombre());
                    texto5.setText(cardAux.getDescripcion());
                }
            }
        
    }//GEN-LAST:event_continuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ataque;
    private javax.swing.JButton Defensa;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Pictur2;
    public static javax.swing.JLabel Picture1;
    private javax.swing.JLabel Priori;
    private javax.swing.JLabel Priori2;
    private javax.swing.JButton continuar;
    private javax.swing.JButton modoAgresivo;
    private javax.swing.JButton modoDefensivo;
    public static javax.swing.JLabel name1;
    public static javax.swing.JLabel name2;
    private javax.swing.JLabel prioridad1;
    private javax.swing.JLabel prioridad2;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel texto5;
    // End of variables declaration//GEN-END:variables
}
