/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea_2;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;

/**
 *
 * @author Gabriel
 */
public class PeleaCom extends javax.swing.JFrame {

    /**
     * Creates new form PeleaCom
     */
    public PeleaCom() {
        initComponents();
        DefensaB.setVisible(false);
        AtaqueB.setVisible(false);
        
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("tarea_2/imagenes/icono.png"));
        return retValue;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Picture1 = new javax.swing.JLabel();
        Pictur2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Priori = new javax.swing.JLabel();
        Priori2 = new javax.swing.JLabel();
        LJ2 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Prioridad = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nametxt2 = new javax.swing.JLabel();
        Defensa = new javax.swing.JButton();
        Ataque = new javax.swing.JButton();
        Aparecer = new javax.swing.JLabel();
        Txt2 = new javax.swing.JLabel();
        Txt3 = new javax.swing.JLabel();
        AtaqueB = new javax.swing.JButton();
        DefensaB = new javax.swing.JButton();
        Active = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SansaStone™ 2.0");
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Picture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/avatar_7cdd33eb8d4a_128.png"))); // NOI18N
        getContentPane().add(Picture1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 120));

        Pictur2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/avatar_eb0c4e0884c0_128.png"))); // NOI18N
        getContentPane().add(Pictur2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Jugador 2:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, -1, 20));

        Priori.setFont(new java.awt.Font("Consolas", 1, 10)); // NOI18N
        Priori.setText("Prioridad: ");
        getContentPane().add(Priori, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, -1, -1));

        Priori2.setFont(new java.awt.Font("Consolas", 1, 10)); // NOI18N
        Priori2.setText("Prioridad: ");
        getContentPane().add(Priori2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        LJ2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LJ2.setText("Jugador 1:");
        getContentPane().add(LJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 100, 20));
        getContentPane().add(Prioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 110, 20));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 130, 20));
        getContentPane().add(Nametxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 80, 20));

        Defensa.setText("Modo Defensivo");
        Defensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefensaActionPerformed(evt);
            }
        });
        getContentPane().add(Defensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 150, 40));

        Ataque.setText("Modo Agresivo");
        Ataque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtaqueActionPerformed(evt);
            }
        });
        getContentPane().add(Ataque, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 130, 40));

        Aparecer.setBackground(new java.awt.Color(255, 255, 255));
        Aparecer.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Aparecer.setForeground(new java.awt.Color(255, 255, 255));
        Aparecer.setText("Elija su Modo,tenga en cuenta que:");
        getContentPane().add(Aparecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 380, 30));

        Txt2.setBackground(new java.awt.Color(255, 255, 255));
        Txt2.setForeground(new java.awt.Color(255, 255, 255));
        Txt2.setText(" -Modo defensivo, dota a la COM de un mazo ordenado con las cartas  de mayor curación al principio.");
        getContentPane().add(Txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        Txt3.setBackground(new java.awt.Color(255, 255, 255));
        Txt3.setForeground(new java.awt.Color(255, 255, 255));
        Txt3.setText("-Modo Agresivo, dota a la COM de un mazo ordenado con las cartas  de mayor ataque al principio. ");
        getContentPane().add(Txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        AtaqueB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/fencing-game-sword-fight-fence-combat-cross-128.png"))); // NOI18N
        AtaqueB.setBorder(null);
        AtaqueB.setBorderPainted(false);
        AtaqueB.setContentAreaFilled(false);
        AtaqueB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AtaqueB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtaqueBActionPerformed(evt);
            }
        });
        getContentPane().add(AtaqueB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, -1, -1));

        DefensaB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/1458264599_piggy_bank_savings_money_investment_budget_finance_icon-icons.com_55332.png"))); // NOI18N
        DefensaB.setBorder(null);
        DefensaB.setBorderPainted(false);
        DefensaB.setContentAreaFilled(false);
        DefensaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefensaBActionPerformed(evt);
            }
        });
        getContentPane().add(DefensaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, -1, -1));

        Active.setText("Active");
        Active.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActiveActionPerformed(evt);
            }
        });
        getContentPane().add(Active, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 670, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/flat-wallpaper-3.png"))); // NOI18N
        Fondo.setPreferredSize(new java.awt.Dimension(720, 1024));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -180, 1040, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public static int Agresivo_Defensivo = 5;
    private void DefensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefensaActionPerformed
        // TODO add your handling code here:
        Aparecer.setVisible(false);  
        Txt2.setVisible(false);
        Txt3.setVisible(false);
        DefensaB.setVisible(true);
        AtaqueB.setVisible(true);
        Defensa.setVisible (false);
        Ataque.setVisible (false);
        Agresivo_Defensivo = 1;        
        
    }//GEN-LAST:event_DefensaActionPerformed
    
    private void AtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtaqueActionPerformed
        // TODO add your handling code here:
        Aparecer.setVisible(false);
        Txt2.setVisible(false);
        Txt3.setVisible(false);  
        DefensaB.setVisible(true);
        AtaqueB.setVisible(true);
        Defensa.setVisible (false);
        Ataque.setVisible (false);
        Agresivo_Defensivo = 0;        
        
    }//GEN-LAST:event_AtaqueActionPerformed
    public int ini = 0;
    public static int AtackOrDefence;
    public static boolean turno = false;
    
    /*public void setAtackorDefence(int AtackOrDefence){
        this.AtackOrDefence = AtackOrDefence;  
    }*/
    private void DefensaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefensaBActionPerformed
        // TODO add your handling code here:
        if (ini !=0){            
            DefensaB.setEnabled(turno);
            AtaqueB.setEnabled(turno);
            AtackOrDefence=0;
        }
        ini++;
    }//GEN-LAST:event_DefensaBActionPerformed

    private void AtaqueBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtaqueBActionPerformed
        // TODO add your handling code here:
        if (ini !=0){
            DefensaB.setEnabled(turno);
            AtaqueB.setEnabled(turno);
            AtackOrDefence=1;
        }
        ini++;
    }//GEN-LAST:event_AtaqueBActionPerformed
    public static int activar=0;
    private void ActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActiveActionPerformed
        // TODO add your handling code here:
        activar = 1;
    }//GEN-LAST:event_ActiveActionPerformed
  
    /**
     * @param args the command line arguments
     */
    
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeleaCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeleaCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeleaCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeleaCom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeleaCom().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Active;
    private javax.swing.JLabel Aparecer;
    private javax.swing.JButton Ataque;
    private javax.swing.JButton AtaqueB;
    private javax.swing.JButton Defensa;
    private javax.swing.JButton DefensaB;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel LJ2;
    public static javax.swing.JLabel Name;
    public static javax.swing.JLabel Nametxt2;
    private javax.swing.JLabel Pictur2;
    public static javax.swing.JLabel Picture1;
    private javax.swing.JLabel Priori;
    private javax.swing.JLabel Priori2;
    private javax.swing.JLabel Prioridad;
    private javax.swing.JLabel Txt2;
    private javax.swing.JLabel Txt3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
