/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea_2;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author JuanPablo
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    /******** Funcion: Constructor registroUnPlayer ********************
    Descripcion: inicializa la ventana donde se efectuara el registro del jugador del juego.
    Parametros:
    void
    Retorno: apertura de la ventana.
    ************************************************/
    public Ventana() {
        initComponents();
    }
    /******** Funcion: getIconImage ********************
    Descripcion: le pone un icono a la ventana
    Parametros:
    * void
    Retorno: void
    ************************************************/
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("tarea_2/imagenes/icono.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Amigo = new javax.swing.JButton();
        Un_jugador = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SansaStone™ 2.0");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setPreferredSize(new java.awt.Dimension(329, 449));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Elija un Modo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 200, 50));

        Amigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/graduates (1).png"))); // NOI18N
        Amigo.setBorder(null);
        Amigo.setBorderPainted(false);
        Amigo.setContentAreaFilled(false);
        Amigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Amigo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/graduates (1).png"))); // NOI18N
        Amigo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/graduates (2).png"))); // NOI18N
        Amigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmigoActionPerformed(evt);
            }
        });
        getContentPane().add(Amigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 70, 70));

        Un_jugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/thinking.png"))); // NOI18N
        Un_jugador.setBorder(null);
        Un_jugador.setBorderPainted(false);
        Un_jugador.setContentAreaFilled(false);
        Un_jugador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Un_jugador.setFocusPainted(false);
        Un_jugador.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/thinking.png"))); // NOI18N
        Un_jugador.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/graduate.png"))); // NOI18N
        Un_jugador.setSelected(true);
        Un_jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Un_jugadorActionPerformed(evt);
            }
        });
        getContentPane().add(Un_jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 70, 80));

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/Door-Exit-Sign-Out-128 (1).png"))); // NOI18N
        salir.setBorder(null);
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/Door_press.png"))); // NOI18N
        salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/Door_press.png"))); // NOI18N
        salir.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/Door_press.png"))); // NOI18N
        salir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/Door_press.png"))); // NOI18N
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("1 Jugador");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Multiplayer");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tarea_2/imagenes/Ultimate-Material-Lollipop-Collection-65.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(1024, 720));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_salirActionPerformed
    /******** Funcion: salirMouseClicked ********************
    Descripcion: Cierra el juego.
    Parametros:
        java.awt.event.ActionEvent evt
    Retorno: void
    ************************************************/
    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked
    
    /******** Funcion: Un_jugadorActionPerformed ********************
    Descripcion: inicializa la ventana para registrar un solo jugador
    Parametros:
        java.awt.event.ActionEvent evt
    Retorno: void
    ************************************************/
    private void Un_jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Un_jugadorActionPerformed
        // TODO add your handling code here:
        registroUnPlayer Multi = new registroUnPlayer();
        Multi.setLocationRelativeTo(null);
        Multi.setVisible(true);
        this.dispose();
               
    }//GEN-LAST:event_Un_jugadorActionPerformed
    
    /******** Funcion: AmigoActionPerformed ********************
    Descripcion: inicializa la ventana para registrar a dos jugadores
    Parametros:
        java.awt.event.ActionEvent evt
    Retorno: void
    ************************************************/
    private void AmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmigoActionPerformed
        // TODO add your handling code here:
        Multiplayer Multi = new Multiplayer();
        Multi.setLocationRelativeTo(null);
        Multi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AmigoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Amigo;
    private javax.swing.JButton Un_jugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
